### PR TITLE
GW-12: Add tailwind and MUI into the repo

### PR DESCRIPTION
**Pull request by Julian-UBC**
- Add TailwindCSS to repo
- Add MUI with corresponding its dependencies to repo

### CODE REVIEW

**Comment by Julian-UBC** [comment]
@gisauweb @chrishadrian can you approve this repo so I can move to the next step

**Review by chrishadrian — COMMENTED** [review]
LGTM!

**Review by chrishadrian — APPROVED** [review]

**Review by jenaarianto — APPROVED** [review]
lgtm!!

**Review by gisauweb — APPROVED** [review]
Good to merge!

**Pull request merged**
